Use MARKETING_VERSION & Bump to 1.13.2
DanTheMan827/ios-app-signer pull request #214
Opened 2022-09-22 08:42 UTC by cxy5014

I have built a new version with a Notarized Developer ID in my repository.

2022-09-22 08:56 UTC, kambala-decapitator requested changes
please remove changing `DevelopmentTeam` / `DEVELOPMENT_TEAM` - I guess that's your own account

2022-09-22 09:02 UTC, kambala-decapitator commented
removing `CFBundleVersion` is a bad idea

2022-09-22 09:32 UTC, kambala-decapitator commented on iOS App Signer.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
to keep existing behavior:
```suggestion
				CURRENT_PROJECT_VERSION = $(MARKETING_VERSION);
```

2022-09-22 09:41 UTC, kambala-decapitator approved these changes

2023-02-13 04:35 UTC, gipnomag commented
> I have built a new version with a Notarized Developer ID in my repository.

2023-02-13 04:39 UTC, gipnomag approved these changes

2023-02-13 04:39 UTC, gipnomag approved these changes

2023-02-13 04:41 UTC, gipnomag requested changes

2023-02-13 04:41 UTC, gipnomag commented on iOS App Signer.xcodeproj/project.pbxproj
>  				CODE_SIGN_STYLE = Automatic;
G

2023-02-13 04:41 UTC, gipnomag commented on iOS App Signer.xcodeproj/project.pbxproj
>  				CODE_SIGN_STYLE = Automatic;
@_ឫទង_

2023-03-07 11:22 UTC, closed without merging